### ISSUE TITLE
Log-Type now allows for other characters

### ISSUE THREAD

**Issue by arka273** [Zimmergren/LogAnalytics.Client#25]
Http request's Log-Type header as described in [https://docs.microsoft.com/en-gb/azure/azure-monitor/platform/data-collector-api](https://docs.microsoft.com/en-gb/azure/azure-monitor/platform/data-collector-api) allows now for other characters and not only the alpha characters: "Log-Type | Specify the record type of the data that is being submitted. Can only contain letters, numbers, and underscore (_), and may not exceed 100 characters.". I have a kind suggestion to you Tobias to update the validation as I use  also numbers in custom log names. Arka

**Comment by Zimmergren** [comment]
Hey @arka273 ,

Thanks for pointing out this updated documentation about the Log-Type. I'll take a look, and will loop back here when I've verified.

**Comment by Zimmergren** [comment]
Fixed in PR #26
