### ISSUE TITLE
Make LogAnalyticsClient dependency injection friendly.

### ISSUE THREAD

**Issue by skalahonza** [Zimmergren/LogAnalytics.Client#28]
It would be great if the LogAnalyticsClient could be registered in the dependency injection container. Also, creating new Http Client on your own is not a good practice. One can easily reuse HttpMessageHandler thanks to pooling: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests

It should be also possible to load workspaceId and sharedKey from configuration or IOptions interface.

**Comment by skalahonza** [comment]
PR: #29

**Comment by Zimmergren** [comment]
Thanks for the contribution, @skalahonza 👏 🎉
