### ISSUE TITLE
Idea: Implement a web-based project that uses DI with the LogAnalyticsClient to verify the e2e workflow, and enhance readme.

### ISSUE THREAD

**Issue by Zimmergren** [Zimmergren/LogAnalytics.Client#31]
To ensure the full circle works for the LogAnalyticsClient, a simple web-based default project that injects the LogAnalyticsClient based on IConfiguration values would be helpful. 

This could also be the base for an enhanced readme experience, explaining how to make use of the LogAnalyticsClient in various scenarios.

**Comment by skalahonza** [comment]
I could help with this. Do you want to include the sample project in the same solution?

**Comment by Zimmergren** [comment]
Great! 

I would probably put the structure next to the original source folder, decoupled from the core solution. 
This way, the example project(s) can reference the latest published NuGet instead of being directly referenced.

Perhaps a folder named `LogAnalytics.Client.Examples` in the repo root folder. Examples: 
- LogAnalytics.Client.Examples\BlazorDemo
- LogAnalytics.Client.Examples\ApiDemo
- LogAnalytics.Client.Examples\ConsoleAppDemo
- etc.

**Comment by skalahonza** [comment]
Does this https://github.com/skalahonza/LogAnalytics.Client/blob/samples/LogAnalytics.Client.Examples/ConsoleAppDemo/Program.cs look ok?

**Comment by Zimmergren** [comment]
Looks great. Thanks!

If possible, let's add a few comments to each of the steps and then we can extract that into an enhanced Readme later, too!

**Comment by Zimmergren** [comment]
Fixed with #32 by @skalahonza
