### ISSUE TITLE
Azure Sovereign Cloud support

### ISSUE THREAD

**Issue by brettmeyerowitz** [Zimmergren/LogAnalytics.Client#38]
Hi,

Thanks for building and maintaining this client.

Would you be able to add Azure Sovereign Cloud support please, i.e.

Commercial = ods.opinsights.azure.com
Government = ods.opinsights.azure.us
China = ods.opinsights.azure.cn

https://docs.microsoft.com/en-us/azure/azure-government/compare-azure-government-global-azure

It would be great to add this as an optional setting during initialization.

Thanks, again,

Brett

**Comment by Zimmergren** [comment]
Hi @brettmeyerowitz ,

Sure, we could add an optional configuration param for the various clouds. 
However, I don't have the capability to try them out or run integration tests for those endpoints. Do you have any suggestions on how to achieve that?

Thanks,
Tobias

**Comment by brettmeyerowitz** [comment]
Thanks for your prompt response!

Unfortunately the only ones I have access to are our corporate ones here - which I cannot expose.

I can, of course, run local integration tests.

Regards,

Brett

**Comment by Zimmergren** [comment]
Fair enough. I'll take a look when I have a few moments, and when it's ready you can run your local integration tests to verify they work. Meanwhile, the only real code change would be the endpoint, and as such, if they support the same APIs it shouldn't be any issue.

I'll ping here with the PR once done.

**Comment by brettmeyerowitz** [comment]
They definitely do support the same API :)

**Comment by Zimmergren** [comment]
Please have a look at #39 , @brettmeyerowitz.

I've ran the integration tests locally for the default configuration (Azure Public cloud), and that looks good. I can't run any integration tests for non-public Azure clouds here. If you could verify/review, that'd be great.

**Comment by Zimmergren** [comment]
Closed with #39
