### ISSUE TITLE
Replace Microsoft.Azure.OperationalInsights dependency

### ISSUE THREAD

**Issue by scottaddie** [Zimmergren/LogAnalytics.Client#45]
Last month, the Azure SDK team [shipped the Azure Monitor Query client library](https://devblogs.microsoft.com/azure-sdk/announcing-the-new-azure-monitor-query-client-libraries/). This [Azure.Monitor.Query](https://www.nuget.org/packages/Azure.Monitor.Query/) package is intended to replace [Microsoft.Azure.OperationalInsights](https://www.nuget.org/packages/Microsoft.Azure.OperationalInsights). Please make plans to migrate. We're actively working toward deprecating the *Microsoft.Azure.OperationalInsights* package.

**Comment by Zimmergren** [comment]
Hey @scottaddie ,

Thanks for the heads up about the deprecation. 
Will take a look. 

Thanks
Tobias

**Comment by Zimmergren** [comment]
Solved in #46 
FYI @scottaddie - version 6.1.0 onward is using Azure.Monitor.Query NuGet 🚀

**Comment by scottaddie** [comment]
@Zimmergren Thank you for migrating so quickly! Well done. 👏

**Comment by Zimmergren** [comment]
You bet @scottaddie ,

Thanks for bringing this to my attention and being proactive. 
Nobody likes deprecated libraries 😄 

All the best,
Tobias.
