### ISSUE TITLE
DateTime values saved without miliseconds

### ISSUE THREAD

**Issue by jmazurpl** [Zimmergren/LogAnalytics.Client#47]
When I save DateTime values to Log Analitics its being saved without miliseconds.

<img width="355" alt="image" src="https://user-images.githubusercontent.com/4668675/144441375-3934bed3-83f7-4e76-9374-fc0e681f6f8a.png">

**Comment by Zimmergren** [comment]
Hey @jmazurpl,

You're right. I verified this behavior recently.

The reason for that date format, is that the headers for the Data Collector API require the RFC 7234 format, which is what we're using right now.

See this: https://docs.microsoft.com/en-us/azure/azure-monitor/logs/data-collector-api#request-headers 

I will try to reach out to someone at MSFT about this, and see if we can learn about other formats that are accepted (and supported).

**Comment by jmazurpl** [comment]
Hi @Zimmergren 

I don't think thats the case. You generate the header values fine. Problem is with DateTime values saved inside the log entry. I took the code example from: https://docs.microsoft.com/en-us/azure/azure-monitor/logs/data-collector-api and it saves the miliseconds. Maybe the problem is with Json serialization. I didn't have time to check it but its next on my list.

**Comment by Zimmergren** [comment]
@jmazurpl, I just ran through a set of E2E tests, and they all are delivered with milliseconds on my end.

![image](https://user-images.githubusercontent.com/4071728/144571876-db53c16b-4c3b-447f-9707-0d6e5b671fe5.png)

The ones where the milliseconds are the same, I suspect are the batch inserts. However, none of my tests have a .000 timestamp. 

What I noticed in your screenshot, and that I suspect is the problem, is that the startTime and endTime fields you have aren't the `TimeGenerated` field. So the actual `TimeGenerated` here does indeed come in correctly.

Is the `startTime_t` and `endTime_t` custom fields in your entity that you're sending?

**Comment by jmazurpl** [comment]
Yes exactly this is what I was trying to say :). I checked the sample code from https://docs.microsoft.com/en-us/azure/azure-monitor/logs/data-collector-api and this code saves miliseconds in my case. I'm still looking for differences in the implementation.

**Comment by jmazurpl** [comment]
@Zimmergren 
Finally the problem was at my side. I had in my project global configuration for Newtonsoft Json that was serializing DateTime without miliseconds. Issue can be closed. Thank you for the support.

**Comment by Zimmergren** [comment]
Thank you for confirming.

**Comment by rboucher** [comment]
Thanks for helping out @Zimmergren. So looks like nothing to change in our docs?

**Comment by Zimmergren** [comment]
Correct @rboucher - all clear 👍🙂
