### ISSUE TITLE
Support for custom tables?

### ISSUE THREAD

**Issue by kirk-marple** [Zimmergren/LogAnalytics.Client#52]
Just ran across this repo, and it looks great for a project I was starting on.  (I'm looking to track our platform usage to build a billing system.)

One question, I was thinking of putting these billable events in a custom table within the Log Workspace.

I read through the code, but I'm not seeing this explicitly supported, or I'm missing it.

Does the current client support custom tables, or would that be something to be added?

**Comment by kirk-marple** [comment]
Oh, I see.  'logType' *is* the custom table name (suffixed with _CL).  Now that makes sense.

**Comment by Zimmergren** [comment]
Hey @kirk-marple . I'm glad got it figured out. 
Here's a blog post I made some years back that covers some additional background, in case that helps further: https://zimmergren.net/building-custom-data-collectors-for-azure-log-analytics/

All the best
Tobias
